export const Actions = {
  USER_JOIN: "USER_JOIN",
  USER_JOINED: "USER_JOINED",
  DISCONNECTED: "disconnected",
  MOVE_PLAYED: "MOVE_PLAYED",
  PLAYER_WON: "PLAYER_WON",
  ROOM_FULL: "ROOM_FULL",
};
